-- Migration number: 0000 generated by teenybase on 2026-05-31T23:08:30.711Z. Do not modify this file.

CREATE TABLE users (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	username TEXT UNIQUE NOT NULL, 
	email TEXT UNIQUE NOT NULL, 
	email_verified BOOLEAN NOT NULL DEFAULT 0, 
	password TEXT NOT NULL, 
	password_salt TEXT NOT NULL, 
	name TEXT NOT NULL, 
	avatar TEXT, 
	role TEXT, 
	meta JSON
);
CREATE TRIGGER tgr_users_raise_on_created_update BEFORE UPDATE OF created ON users BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_users_update_updated_on_update AFTER UPDATE ON users BEGIN UPDATE users SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;