-- Migration number: 0001 generated by teenybase on 2026-05-31T23:08:30.711Z. Do not modify this file.

CREATE TABLE posts (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	author_id TEXT NOT NULL REFERENCES users(id), 
	title TEXT NOT NULL, 
	slug TEXT UNIQUE NOT NULL, 
	excerpt TEXT, 
	cover_image TEXT, 
	body TEXT NOT NULL, 
	tags TEXT, 
	published BOOLEAN, 
	published_at TIMESTAMP, 
	ai_generated BOOLEAN
);
CREATE INDEX idx_posts_slug ON posts (slug);
CREATE INDEX idx_posts_published ON posts (published);
CREATE INDEX idx_posts_author_id ON posts (author_id);
CREATE TRIGGER tgr_posts_raise_on_created_update BEFORE UPDATE OF created ON posts BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_posts_update_updated_on_update AFTER UPDATE ON posts BEGIN UPDATE posts SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;