-- Migration number: 0002 generated by teenybase on 2026-05-31T23:08:30.711Z. Do not modify this file.

CREATE TABLE content (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	section TEXT UNIQUE NOT NULL, 
	draft TEXT, 
	published TEXT
);
CREATE INDEX idx_content_section ON content (section);
CREATE TRIGGER tgr_content_raise_on_created_update BEFORE UPDATE OF created ON content BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_content_update_updated_on_update AFTER UPDATE ON content BEGIN UPDATE content SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;