-- Migration number: 0003 generated by teenybase on 2026-05-31T23:08:30.711Z. Do not modify this file.

CREATE TABLE links (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	author_id TEXT NOT NULL REFERENCES users(id), 
	title TEXT NOT NULL, 
	url TEXT NOT NULL, 
	note TEXT, 
	kind TEXT, 
	tags TEXT, 
	published BOOLEAN, 
	published_at TIMESTAMP
);
CREATE INDEX idx_links_published ON links (published);
CREATE INDEX idx_links_published_at ON links (published_at);
CREATE INDEX idx_links_author_id ON links (author_id);
CREATE TRIGGER tgr_links_raise_on_created_update BEFORE UPDATE OF created ON links BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_links_update_updated_on_update AFTER UPDATE ON links BEGIN UPDATE links SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;