-- Migration number: 0004 generated by teenybase on 2026-06-13T12:53:55.171Z. Do not modify this file.

CREATE TABLE views (
	id TEXT PRIMARY KEY NOT NULL, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	path TEXT UNIQUE NOT NULL, 
	count INTEGER
);
CREATE INDEX idx_views_path ON views (path);
CREATE INDEX idx_views_count ON views (count);
CREATE TRIGGER tgr_views_raise_on_created_update BEFORE UPDATE OF created ON views BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;
CREATE TRIGGER tgr_views_update_updated_on_update AFTER UPDATE ON views BEGIN UPDATE views SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id AND OLD.updated = NEW.updated; END;