#!/usr/bin/env node
/**
 * DEMO-ONLY: wire the daily demo-reset cron into the build output.
 *
 * This is a no-op unless the build sets PUBLIC_DEMO_MODE=1, so a normal clone
 * deploys a plain portfolio Worker with no scheduled task. The public demo
 * deployment turns it on (a build var), and then this runs after `astro build`
 * to:
 *
 *   1. write dist/server/cron-entry.mjs — a thin wrapper that re-exports the
 *      adapter's fetch handler and adds a scheduled() handler that POSTs to
 *      /internal/reset (token from the RESET_TOKEN secret), and
 *   2. point the generated wrangler.json `main` at that wrapper and add the cron
 *      trigger.
 *
 * Schedule defaults to daily at 00:00 UTC; override with DEMO_CRON.
 * Wired as the second half of the `build` script in package.json.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const DEMO_MODE =
  process.env.PUBLIC_DEMO_MODE === '1' || process.env.PUBLIC_DEMO_MODE === 'true';

if (!DEMO_MODE) {
  // Plain build — leave the adapter's Worker entry untouched.
  process.exit(0);
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const serverDir = join(root, 'dist', 'server');
const wjPath = join(serverDir, 'wrangler.json');
const entryPath = join(serverDir, 'entry.mjs');

if (!existsSync(wjPath) || !existsSync(entryPath)) {
  console.error('[postbuild-cron] dist/server not found — did `astro build` run? Skipping.');
  process.exit(0);
}

const crons = [process.env.DEMO_CRON || '0 0 * * *'];

const wrapper = `// Generated by scripts/postbuild-cron.mjs (PUBLIC_DEMO_MODE) — do not edit.
// Wraps the @astrojs/cloudflare Worker entry with a scheduled() handler that
// triggers the daily demo database reset.
import app from './entry.mjs';

export default {
  fetch: (request, env, ctx) => app.fetch(request, env, ctx),
  async scheduled(event, env, ctx) {
    const base = String(env.APP_URL || 'https://astro-monograph-teenybase.theserverless.dev').replace(/\\/$/, '');
    const req = new Request(base + '/internal/reset', {
      method: 'POST',
      headers: { 'x-reset-token': env.RESET_TOKEN || '', Origin: base },
    });
    ctx.waitUntil(
      app.fetch(req, env, ctx)
        .then((r) => r.text())
        .then((t) => console.log('[demo-reset]', t))
        .catch((e) => console.error('[demo-reset] failed', e)),
    );
  },
};
`;

writeFileSync(join(serverDir, 'cron-entry.mjs'), wrapper);

const wj = JSON.parse(readFileSync(wjPath, 'utf8'));
wj.main = 'cron-entry.mjs';
wj.triggers = { crons };
writeFileSync(wjPath, JSON.stringify(wj));

console.log(`[postbuild-cron] demo mode: wrapped entry + scheduled reset (crons: ${crons.join(', ')})`);
