#!/usr/bin/env node
/**
 * Add the daily demo-reset cron to the build output.
 *
 * The @astrojs/cloudflare adapter owns the Worker entry (dist/server/entry.mjs,
 * which only exports `fetch`) and the deploy config (dist/server/wrangler.json,
 * used by `wrangler deploy` via the .wrangler/deploy/config.json redirect). Rather
 * than patch the adapter's generated code, this runs after `astro build` to:
 *
 *   1. write dist/server/cron-entry.mjs — a thin wrapper that re-exports the
 *      adapter's fetch handler and adds a scheduled() handler that POSTs to
 *      /internal/reset (token from the RESET_TOKEN secret), and
 *   2. point the generated wrangler.json `main` at that wrapper and add the cron
 *      trigger.
 *
 * Wired as the second half of the `build` script in package.json.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const serverDir = join(root, 'dist', 'server');
const wjPath = join(serverDir, 'wrangler.json');
const entryPath = join(serverDir, 'entry.mjs');

if (!existsSync(wjPath) || !existsSync(entryPath)) {
  console.error('[postbuild-cron] dist/server not found — did `astro build` run? Skipping.');
  process.exit(0);
}

// Keep the schedule in sync with the root wrangler.jsonc (single source of truth);
// fall back to daily at midnight UTC.
function readCrons() {
  try {
    const src = readFileSync(join(root, 'wrangler.jsonc'), 'utf8');
    const m = src.match(/"crons"\s*:\s*\[([^\]]*)\]/);
    if (m) {
      const arr = m[1].split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
      if (arr.length) return arr;
    }
  } catch { /* fall through */ }
  return ['0 0 * * *'];
}

const wrapper = `// Generated by scripts/postbuild-cron.mjs — do not edit.
// Wraps the @astrojs/cloudflare Worker entry with a scheduled() handler that
// triggers the daily demo database reset.
import app from './entry.mjs';

export default {
  fetch: (request, env, ctx) => app.fetch(request, env, ctx),
  async scheduled(event, env, ctx) {
    const base = String(env.APP_URL || 'https://astro-monograph-teenybase.theserverless.dev').replace(/\\/$/, '');
    const req = new Request(base + '/internal/reset', {
      method: 'POST',
      headers: { 'x-reset-token': env.RESET_TOKEN || '', Origin: base },
    });
    ctx.waitUntil(
      app.fetch(req, env, ctx)
        .then((r) => r.text())
        .then((t) => console.log('[demo-reset]', t))
        .catch((e) => console.error('[demo-reset] failed', e)),
    );
  },
};
`;

writeFileSync(join(serverDir, 'cron-entry.mjs'), wrapper);

const wj = JSON.parse(readFileSync(wjPath, 'utf8'));
wj.main = 'cron-entry.mjs';
wj.triggers = { crons: readCrons() };
writeFileSync(wjPath, JSON.stringify(wj));

console.log(`[postbuild-cron] wrapped entry + scheduled reset (crons: ${wj.triggers.crons.join(', ')})`);
